#: Operation ids
ops = [
    "transfer",
    "limit_order_create",
    "limit_order_cancel",
    "call_order_update",
    "fill_order",
    "account_create",
    "account_update",
    "account_whitelist",
    "account_upgrade",
    "account_transfer",
    "asset_create",
    "asset_update",
    "asset_update_bitasset",
    "asset_update_feed_producers",
    "asset_issue",
    "asset_reserve",
    "asset_fund_fee_pool",
    "asset_settle",
    "asset_global_settle",
    "asset_publish_feed",
    "witness_create",
    "witness_update",
    "proposal_create",
    "proposal_update",
    "proposal_delete",
    "withdraw_permission_create",
    "withdraw_permission_update",
    "withdraw_permission_claim",
    "withdraw_permission_delete",
    "committee_member_create",
    "committee_member_update",
    "committee_member_update_global_parameters",
    "vesting_balance_create",
    "vesting_balance_withdraw",
    "worker_create",
    "custom",
    "assert",
    "balance_claim",
    "override_transfer",
    "transfer_to_blind",
    "blind_transfer",
    "transfer_from_blind",
    "asset_settle_cancel",
    "asset_claim_fees",
    "fba_distribute",
    "bid_collateral",
    "execute_bid",
    "reserved47",
    "reserved48",
    "reserved49",
    "reserved50",
    "reserved51",
    "reserved52",
    "reserved53",
    "reserved54",
    "reserved55",
    "reserved56",
    "reserved57",
    "reserved58",
    "reserved59",
    "reserved60",
    "reserved61",
    "reserved62",
    "reserved63",
    "reserved64",
    "reserved65",
    "reserved66",
    "reserved67",
    "reserved68",
    "reserved69",
    "reserved70",
    "reserved71",
    "reserved72",
    "reserved73",
    "reserved74",
    "reserved75",
    "reserved76",
    "reserved77",
    "reserved78",
    "reserved79",
    "reserved80",
    "reserved81",
    "reserved82",
    "reserved83",
    "reserved84",
    "reserved85",
    "reserved86",
    "reserved87",
    "reserved88",
    "reserved89",
    "reserved90",
    "reserved91",
    "reserved92",
    "reserved93",
    "reserved94",
    "reserved95",
    "reserved96",
    "reserved97",
    "reserved98",
    "reserved99",
    "cancel_vesting"
]
operations = {o: ops.index(o) for o in ops}


def getOperationNameForId(i):
    """ Convert an operation id into the corresponding string
    """
    for key in operations:
        if int(operations[key]) is int(i):
            return key
    return "Unknown Operation ID %d" % i
